Algoritmo "TEMPERATURA"

Var

 F, C : real
 escala:caractere

Inicio

escreva("Voce vai digitar a temperatura em qual escala (C/F)?")
leia(escala)

se escala = "F"entao
   escreva("Digite a temperatura em Fahrenheit:")
   leia(F)

   C <- 5/9 * (F - 32)
   
   escreva("Temperatura equivalente em Celsius:", C:4:2)
senão
   escreva("Digite a temperatura em Celsius:")
   leia(C)
   
   F <- C * 9 / 5 + 32
    
   escreva("Temperatura equivalente em Fahrenheit:", F:4:2)
 fimse


Fimalgoritmo